workflows:
  build-mobywatel:
    name: Build Mobywatel iOS
    instance_type: mac_mini_m2
    max_build_duration: 60
    environment:
      xcode: latest
      vars:
        PROJECT_DIR: "App"
    scripts:
      - name: Build
        script: |
          cd $PROJECT_DIR
          xcodebuild build \
            -scheme App \
            -sdk iphoneos \
            -configuration Release \
            CODE_SIGNING_ALLOWED=NO \
            CODE_SIGNING_REQUIRED=NO \
            CODE_SIGN_IDENTITY="" \
            -derivedDataPath build
    artifacts:
      - path: "**/*.app"
      - path: "**/*.ipa"